### ISSUE TITLE
Example code request

### ISSUE THREAD

**Issue by andreasntr** [bouzidanas/streamlit-float#4]
Can we have the code related to https://float-demo.streamlit.app/ ? It would be very interesting to know how to build a fixed navbar like that

Thank you

**Comment by bouzidanas** [comment]
Hi! Appreciate the interest. Its in this repo here: [https://github.com/bouzidanas/streamlit-float/blob/master/streamlit_float/demo.py](https://github.com/bouzidanas/streamlit-float/blob/master/streamlit_float/demo.py)

I just glanced at the demo and it looks like some things broke. I will have to look into that later. It could be that I fiddle with stuff and commited changes before returning things to working order.
